name = "glitch-agents"
main = "dist/index.mjs"
compatibility_date = "2024-03-12"

[build]
command = "pnpm build"
watch_dir = "src"

[build.upload]
format = "modules"
main = "dist/index.mjs"
dir = "dist"

[env.production]
name = "glitch-agents-prod"

[env.staging]
name = "glitch-agents-staging" 